Booking/urls.py
from django.urls import path
from .views import rooms, books, bookingView, roomdetailview, CancelBookingView

app_name = 'Booking'

urlpatterns = [
    path('rooms/', rooms, name='rooms'),
    path('books/', books.as_view(), name='books'),
    path('book/', bookingView.as_view(), name='booking_view'),
    path('room/<category>', roomdetailview.as_view(), name='roomdetailview'),
    path('booking/cancel/<pk>', CancelBookingView.as_view(), name='CancelBookingView'),
]

HotelBookingSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Booking.views import homepage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage),
    path('', include('Booking.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Booking/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse, reverse_lazy
# Create your models here.

class room(models.Model):
    room_type = (
        ('SBD', 'SINGLE BED'), # what kind of room it is
        ('DBD', 'DOUBLE BED'),
        ('VIP', 'DELUXE ROOM'),
    
    )
    roomnumber = models.IntegerField()
    category = models.CharField(max_length=3, choices=room_type)
    beds = models.IntegerField()
    capacity = models.IntegerField() # how many people can be help within the room

    def __str__(self):
        return f'{self.roomnumber}. {self.category} with {self.beds} beds for {self.capacity} people'
        #returns a string with all the room info
        
class book(models.Model):
    # code for the variable for user and room taken from stack overflow
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey(room, on_delete=models.CASCADE)
    checking_in = models.DateTimeField()
    checking_out = models.DateTimeField()

    def __str__(self):
        return f'{self.user} has booked {self.room} at {self.checking_in} to {self.checking_out}' 

    def get_room_category(self): #gets the actual room type from the key to display it on the html
        room_categories = dict(self.room.room_type)
        room_category = room_categories.get(self.room.category)
        return room_category

    def get_cancel_booking_url(self): #code helped from stack overflow
        return reverse_lazy("Booking:CancelBookingView", args=[self.pk])

Booking/forms.py
from django import forms

class availibleFrom(forms.Form):
    checking_in = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M", ])
    checking_out = forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M", ])

Booking/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import ListView, FormView, View, DeleteView
from django.urls import reverse, reverse_lazy
from .models import room, book
from .forms import availibleFrom
from Booking.book_functions.availibility import check_availibility
# Create your views here.

def rooms(request): #gets all the values of the room and sorts it into a list
    rooms = room.objects.all()[0]
    room_categories = dict(room.room_type) #creates a dictionary
    room_values = room_categories.values()
    room_list=[]

    for room_type in room_categories: # loops through the list to create a list of room types to iterate through for the html
        rooms = room_categories.get(room_type)
        room_url = reverse('Booking:roomdetailview', kwargs={'category': room_type})
        room_list.append((rooms, room_url))
    context = {
        "room_list": room_list,
        
    }
    print(room_list)
    return render(request, 'roominfoview.html', context)

class books(ListView):
    model = book
    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_staff:
            booking_list = book.objects.all()
            return booking_list
        else:
            booking_list = book.objects.filter(user=self.request.user)
            return booking_list


class roomdetailview(View):
    def get(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        form = availibleFrom()
        room_list = room.objects.filter(category=category)
        rooms = room_list[0]

        if len(room_list) > 0:
            rooms = room_list[0]
            room_category = dict(room.room_type).get(rooms.category, None)  #creates a dictonaty of the room catergories/types
            context = {
                "room_category": room_category,
                "form": form,
            }
            return render(request, 'roomdetailview.html', context)
        else: 
            return HttpResponse("this room does not exist!")


    def post(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        room_list = room.objects.filter(category=category)
        form = availibleFrom(request.POST)

        if form.is_valid():
            data = form.cleaned_data

        available_room_list = []
        for rooms in room_list:
            if check_availibility(rooms, data['checking_in'], data['checking_out']):
                available_room_list.append(rooms)

        if len(available_room_list) > 0:
            availroom = available_room_list[0]
            availbook = book.objects.create(
                user = self.request.user,
                room = availroom,
                checking_in = data['checking_in'],
                checking_out = data['checking_out'],
            )
            availbook.save()
            return render(request, 'confirmation.html')
            
        else:
            return render(request, 'alreadybooked.html')


class bookingView(FormView):
    form_class = availibleFrom
    template_name = 'availibile_form.html'

    def form_valid(self, form):
        data = form.cleaned_data
        room_list = room.objects.filter(catergory=data['room_type'])
        available_room_list = []
        for rooms in room_list:
            if check_availibility(rooms, data['checking_in'], data['checking_out']):
                available_room_list.append(rooms)

        if len(available_room_list) > 0:
            availroom = available_room_list[0]
            availbook = book.objects.create(
                user = self.request.user,
                room = availroom,
                checking_in = data['checking_in'],
                checking_out = data['checking_out'],
            )
            availbook.save()
            return HttpResponse(availbook)
        else:
            return HttpResponse('this is booked already!, Please book into another time slot.')

class CancelBookingView(DeleteView):
    model = book
    success_url = reverse_lazy('Booking:books')

def homepage(request):
    return render(request, "homepage.html")

templates/Booking/book_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'Booking/css/roomdetail.css' %}">

</head>

<body>

    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="https://res.cloudinary.com/dzcsl3wxe/image/upload/v1671079411/photo-1519710164239-da123dc03ef4_cusy1s.avif">
        </div>

        <!-- Room Details -->
        <div class="room">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="/backs"><i class="fas fa-arrow-alt-circle-left">back</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="room-info">
                <h1>{{room_category}}</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}
                <h2>Are you sure you want to cancel this booking? </h2>
                <h3>{{book.room.number}} {{book.get_room_category}} {{book}}</h3>
                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit">Cancel the Room</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>

<style>
    *{
    padding:0;
    margin:0;
    box-sizing: border-box;
}
body{
    background-color: rgb(46, 47, 48);
    color: rgb(236, 235, 228);
    font-family: sans-serif;
    line-height: 1.25;
    height: 100vh;
}

/* Main Divs */
.content {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    width:100%;
    justify-content: left;
}

.image{
    flex: 0.3;
}

.room{
    flex:0.5;
    margin: 2rem;
    display:flex;
    text-align: left;
    align-items: start;  
    flex-direction: column;
}

/* Sub Divs */

.home{
    flex: 0.2;
}
.room-info{
    flex: 0.4;
    margin: 5rem 1rem;
    
}

form{
    display: flex;
    flex: 0.4 1 auto;
    flex-direction: column;
}

/* Inside Sub Divs */

.image img{
    flex:1;
    max-height: 99.2vh;
}

i{
    color:#dfdfdf;
    font-size: 2rem;
}

/* Form's CSS */

.input-div{
    flex: 1 1 auto;
    margin:1rem;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
}

input, button{
    flex:1;
    width:300px;
    border-radius: 0.5rem;
    line-height: 1.5;
    font-size: 1.5rem;
    color: #555;
}

button{
    background-color: #dfdfdf;
    color:rgb(6, 137, 245);
    outline:none;
}

button:hover{
    color:#dfdfdf;
    background-color: rgb(6, 137, 245);
}
</style>

templates/Booking/book_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking List</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'Booking/css/booking_listpage.css' %}">
</head>

<body>
    <div class="content">
        <div class="header">
            <div class="headings">
                <h1>Your Bookings</h1>
                <h2>Welcome dear {{user}}</h2>
            </div>
            <div class="home">
                <!-- Div 1: Back to Home -->
                <div class="home">
                    <a href="/rooms"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
                </div>
            </div>

        </div>

        <div class="bookings">
            {% for booking in book_list %}
            <div class="booking">
                <img src="https://res.cloudinary.com/dzcsl3wxe/image/upload/v1671079568/cartoon-bed-6_mxdixm.gif"
                    alt="">
                <div class="category">
                    <h2>{{booking.get_room_category}} Suite</h2>
                </div>
                <div class="from">
                    <h3>From: {{booking.checking_in}}</h3>
                </div>
                <div class="to">
                    <h3>To: {{booking.checking_out}}</h3>
                </div>
                <div class="beds">
                    <h3>Beds: {{booking.room.beds}}</h3>
                </div>
                <div class="capacity">
                    <h3>Capacity: {{booking.room.capacity}}</h3>
                </div>
                <div class="cancel"><a href="{{booking.get_cancel_booking_url}}" class="invisible"><i
                            class="far fa-2x fa-times-circle"> Cancel
                            Booking</i></a></div>

            </div>
            {% endfor %}
        </div>
</body>

</html>

<style>
    *{
    padding:0;
    margin:0;
    box-sizing: border-box;
}
body{
    font-family: sans-serif;
    background-color: rgb(46, 47, 48);
    color: rgb(236, 235, 228);
    line-height: 1.5;
    font-size: 1.2rem;
    text-align: center;
}

.content{
    display: flex;
    flex-direction: column;
}

.header{
    flex: 1;
    display: flex;
    flex-flow: row-reverse wrap;
    justify-content: space-evenly;
    align-items: center;
}
.headings{
    flex:1.5;
}
.home{
    flex:0.1;
    
}

.bookings{
    margin-top: 2rem;
    flex:1;
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: space-evenly;
}
.booking{
    flex:1;
    max-width:20vw;
    min-width: 20rem;
    text-align: left;
    border: 1px solid #dbdbdb;
    padding:1rem;
    border-radius: 0.75rem;
    margin:1rem;
}
.booking:hover{
    cursor: pointer;

}
img{
    max-width: 100%;
}
a i{
    margin: 1rem;
    color:rgb(236, 235, 228);
    text-decoration: none;
}
.home a i{
    font-size: 1.7rem;

}

h1,h2{
    margin:1rem;
}
.booking a i{
    font-size: 1.1rem;
    visibility: hidden;
  opacity: 0;
  transition: visibility 0s, opacity 0.5s linear;
}

.booking:hover .cancel a i,.cancel a i:hover{
    visibility: visible;
  opacity: 1;
}
.cancel a i:hover{
    color: rgb(206, 43, 43);
    
}
</style>

templates/Booking/room_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room List</title>
</head>
<body>
    {% for rooms in room_list %}
    <h2>{{rooms}}</h2>
    {% endfor %}
</body>
</html>

templates/alreadybooked.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome#</title>
    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'Booking/css/roomspage.css' %}">
</head>

<body>
    <div id="brand">
        <h1>whoops! this is already booked</h1>
        <p><a href="/rooms">Home</a></p>
        <p><a href="/books">Bookings</a></p>
    </div>  
</body>

</html>

<style>
    /* Root CSS */
*{
    padding:0;
    margin:0;
    box-sizing: border-box;
}
body{
    background-color: rgb(46, 47, 48);
    color: rgb(236, 235, 228);
    font-family: sans-serif;
    line-height: 1.25;
}

/*Brand CSS */
#brand{
    text-align: center;
    font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
    font-size: 3rem;
    margin: 1.5rem;
}

/* Main Div */
.content {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    width:100%;
    justify-content: space-evenly;
}

/* Room Divs */
.room{
    max-width:20%;
    min-width: 200px;
    text-align: center;
    border-radius: 1rem;
    padding:1rem;
    margin:0.5rem;
    background-color: #444;
    flex: 1;
}

.room:hover{
    background-color: #353535;
}

/* Inside Room Divs */
h2{
    margin: 0.25rem;
}
a{
    text-decoration: none;
    color: #dbdbdb;
}
img{
    max-width:90%;
}


</style>

templates/availibile_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book a room here!</title>
</head>
<body>
    <form action="" method="POST">
        {{form.as_p}}
        {% csrf_token %}
        <button type="submit">Book Room!</button>
    </form>
</body>
</html>

templates/confirmation.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome#</title>
    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'Booking/css/roomspage.css' %}">
</head>

<body>
    <div id="brand">
        <h1>Thank you for booking!</h1>
        <p><a href="/rooms">Home</a></p>
        <p><a href="/books">Bookings</a></p>
    </div>  
</body>

</html>

<style>
    /* Root CSS */
*{
    padding:0;
    margin:0;
    box-sizing: border-box;
}
body{
    background-color: rgb(46, 47, 48);
    color: rgb(236, 235, 228);
    font-family: sans-serif;
    line-height: 1.25;
}

/*Brand CSS */
#brand{
    text-align: center;
    font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
    font-size: 3rem;
    margin: 1.5rem;
}

/* Main Div */
.content {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    width:100%;
    justify-content: space-evenly;
}

/* Room Divs */
.room{
    max-width:20%;
    min-width: 200px;
    text-align: center;
    border-radius: 1rem;
    padding:1rem;
    margin:0.5rem;
    background-color: #444;
    flex: 1;
}

.room:hover{
    background-color: #353535;
}

/* Inside Room Divs */
h2{
    margin: 0.25rem;
}
a{
    text-decoration: none;
    color: #dbdbdb;
}
img{
    max-width:90%;
}


</style>

templates/homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'Booking/css/roomspage.css' %}">
</head>

<body>
    <div id="brand">
        <h1>Welcome to Hotel ibrahim</h1>
        <nav>
            <ul><a href="/accounts/signup/">register</a></ul>
            <ul><a href="/accounts/login/">login</a></ul>
        </nav>
    </div>  
</body>

</html>

<style>
    /* Root CSS */
*{
    padding:0;
    margin:0;
    box-sizing: border-box;
}
body{
    background-color: rgb(46, 47, 48);
    color: rgb(236, 235, 228);
    font-family: sans-serif;
    line-height: 1.25;
}

/*Brand CSS */
#brand{
    text-align: center;
    font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
    font-size: 3rem;
    margin: 1.5rem;
}

/* Main Div */
.content {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    width:100%;
    justify-content: space-evenly;
}

/* Room Divs */
.room{
    max-width:20%;
    min-width: 200px;
    text-align: center;
    border-radius: 1rem;
    padding:1rem;
    margin:0.5rem;
    background-color: #444;
    flex: 1;
}

.room:hover{
    background-color: #353535;
}

/* Inside Room Divs */
h2{
    margin: 0.25rem;
}
a{
    text-decoration: none;
    color: #dbdbdb;
}
img{
    max-width:90%;
}


</style>

templates/roomdetailview.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'Booking/css/roomdetail.css' %}">

</head>

<body>  
    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="https://res.cloudinary.com/dzcsl3wxe/image/upload/v1671079411/photo-1519710164239-da123dc03ef4_cusy1s.avif">
        </div>

        <!-- Room Details -->
        <div class="room">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="/rooms"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="room-info">
                <h1>{{room_category}}</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_checking_in">Check In : </label>
                    <input type="datetime-local" id="id_checking_in" name="checking_in">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_checking_out">Check Out : </label>
                    <input type="datetime-local" id="id_checking_out" name="checking_out">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit">Book the Room</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>

<style>
    /* Root CSS */

*{
    padding:0;
    margin:0;
    box-sizing: border-box;
}
body{
    background-color: rgb(46, 47, 48);
    color: rgb(236, 235, 228);
    font-family: sans-serif;
    line-height: 1.25;
    height: 100vh;
}

/* Main Divs */
.content {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    width:100%;
    justify-content: left;
}

.image{
    flex: 0.3;
}

.room{
    flex:0.5;
    margin: 2rem;
    display:flex;
    text-align: left;
    align-items: start;  
    flex-direction: column;
}

/* Sub Divs */

.home{
    flex: 0.2;
}
.room-info{
    flex: 0.4;
    margin: 5rem 1rem;
    
}

form{
    display: flex;
    flex: 0.4 1 auto;
    flex-direction: column;
}

/* Inside Sub Divs */

.image img{
    flex:1;
    max-height: 99.2vh;
}

i{
    color:#dfdfdf;
    font-size: 2rem;
}

/* Form's CSS */

.input-div{
    flex: 1 1 auto;
    margin:1rem;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
}

input, button{
    flex:1;
    width:300px;
    border-radius: 0.5rem;
    line-height: 1.5;
    font-size: 1.5rem;
    color: #555;
}

button{
    background-color: #dfdfdf;
    color:rgb(6, 137, 245);
    outline:none;
}

button:hover{
    color:#dfdfdf;
    background-color: rgb(6, 137, 245);
}
</style>

templates/roominfoview.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel ibrahim</title>
    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'Booking/css/roomspage.css' %}">
</head>
<div id="leftside">
    <h1><a href="/accounts/logout/">logout</a></h1>
</div>
<div id="rightside">
    <h1><a href="/books">Bookings</a></h1>
</div>

<body>
    <!-- Brand -->
    <h1 id="brand">Hotel ibrahim Ci</h1>

    <!-- Main Content -->
    <div class="content">
        {% for room_category, room_url in room_list %}
        <div class="room">
            <a href="{{room_url}}">
                <img
                    src="https://res.cloudinary.com/dzcsl3wxe/image/upload/v1671079411/photo-1519710164239-da123dc03ef4_cusy1s.avif">

                <h2>{{room_category}} SUITE</h2>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi</p>
            </a>
        </div>
        {% endfor %}


    </div>
</body>

</html>

<style>
    /* Root CSS */
*{
    padding:0;
    margin:0;
    box-sizing: border-box;
}
body{
    background-color: rgb(46, 47, 48);
    color: rgb(236, 235, 228);
    font-family: sans-serif;
    line-height: 1.25;
}

/*Brand CSS */
#brand{
    text-align: center;
    font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
    font-size: 3rem;
    margin: 1.5rem;
}

/* Main Div */
.content {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    width:100%;
    justify-content: space-evenly;
}

/* Room Divs */
.room{
    max-width:20%;
    min-width: 200px;
    text-align: center;
    border-radius: 1rem;
    padding:1rem;
    margin:0.5rem;
    background-color: #444;
    flex: 1;
}

.room:hover{
    background-color: #353535;
}

/* Inside Room Divs */
h2{
    margin: 0.25rem;
}
a{
    text-decoration: none;
    color: #dbdbdb;
}
img{
    max-width:90%;
}


</style>